### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by onsoul** [souliot/siot-mgo-pool#1]
冒昧提出ISSUES，从您的组件注释里看出您是个中国人，这个组件很有用。
另外我们想伸出橄榄枝，发这条信息是希望您可以加入我们的合伙阵营。
最近我们在做一个国际IM系统，框架组成里有一部分是GO与MongoDB，如果大神有意向请联系onsoul#qq.com 。 
如果大神已经拥有固定的工作并不想换环境，我也很希望可以利用空闲时间一起维护这个组件并一直使用它！

**Comment by souliot** [comment]
您好，首先说明下，该库是基于beego的orm库改写的，许多功能目前还不完善，会在后续开发中更新修复。
我这边会尽快编写使用文档，有任何问题欢迎提出！

**Comment by onsoul** [comment]
好的！谢谢
